#!/usr/bin/env python

from mininet.cli import CLI

import sys
import os
import topology.mininet_topology as topology


if __name__ == "__main__":
    os.system("cat tools/turtles_art")
    # Create UC Topology instance
    topo = topology.MyTopo()
    CLI(topo.getNet())
